export const MEMBERS = [
  { images: "/images/members/1.png", name: "Fahrizil Fauzi", position: "K3LH" },
  { images: "/images/members/2.png", name: "Dhony Irmaniansyah", position: "Operasional Produksi" },
  { images: "/images/members/3.png", name: "Ikhtafia Harnum Aditya", position: "Pengembangan Produk & Energic Material" },
  { images: "/images/members/4.png", name: "Nabila Desy Rahmawati", position: "Pengembangan Produk & Energic Material" },
  { images: "/images/members/5.png", name: "Dina Amalina", position: "Sistem Teknologi Informasi" },
  { images: "/images/members/6.png", name: "Joel Bornardo M S", position: "Pengembangan Produk & Energic Material" },
  { images: "/images/members/7.png", name: "Haniel Christo Hong Sitorus", position: "Pengembangan Produk & Energic Material" },
  { images: "/images/members/8.png", name: "Ma'rif Ardhi Saputro", position: "Sistem Manajemen" },
  { images: "/images/members/9.png", name: "Latisa Stevi Alivia", position: "Pengendalian Kualitas" },
  { images: "/images/members/10.png", name: "Fina Shafirna Mustaqiem", position: "Pengembangan Produk & Energic Material" },
  { images: "/images/members/11.png", name: "Syifa Yunia Briliani", position: "Komunikasi Perusahaan" },
  { images: "/images/members/12.png", name: "Tafuzi Fauriana", position: "Komunikasi Perusahaan" },
  { images: "/images/members/13.png", name: "Muhammad Fathan Nabil Al Badi", position: "Operasional Produksi" },
  { images: "/images/members/14.png", name: "Muhammad Yusuf Andrika", position: "System Analyst" },
  { images: "/images/members/15.png", name: "Isaura Qinthara Heriswan", position: "Sistem Teknologi Informasi" },
  { images: "/images/members/16.png", name: "Muhammad Trisna Putra Pratama", position: "Pengembangan Produk & Energic Material" },
  { images: "/images/members/17.png", name: "Cornelius Abram Galia JP", position: "Pengembangan Produk & Energic Material" },
  { images: "/images/members/18.png", name: "M. Adrian Rezki Anggara MS", position: "Pengendalian Kualitas" },
];
