export const MEMBERS = [
    { images: "/images/members/1.png" },
    { images: "/images/members/2.png" },
    { images: "/images/members/3.png" },
    { images: "/images/members/4.png" },
    { images: "/images/members/5.png" },
    { images: "/images/members/6.png" },
    { images: "/images/members/7.png" },
    { images: "/images/members/8.png" },
    { images: "/images/members/9.png" },
    { images: "/images/members/10.png" },
    { images: "/images/members/11.png" },
    { images: "/images/members/12.png" },
    { images: "/images/members/13.png" },
    { images: "/images/members/14.png" },
    { images: "/images/members/15.png" },
    { images: "/images/members/16.png" },
    { images: "/images/members/17.png" },
    { images: "/images/members/18.png" },
];
